server:
  port: 8092
  servlet:
    session:
      cookie:
        max-age: 600

#关于spring的配置
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    format:
      date: yyyy-MM-dd
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  #Redis配置
  redis:
    port: 6379
    host: 211.69.238.77
    password: zdk13696086376.
  #缓存配置
  cache:
    type: redis

  #数据源配置
  datasource:
    name: mysql_druid
    type: com.alibaba.druid.pool.DruidDataSource
    #druid相关配置
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      #基本属性
      url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf8
      username: root
      password: root
      #配置初始化大小/最小/最大
      initialSize: 5
      minIdle: 5
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 60000
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 300000
      validationQuery: SELECT 1 FROM DUAL
      poolPreparedStatements: true
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      max-pool-prepared-statement-per-connection-size: 20
      ### 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: stat,wall,log4j2
      useGlobalDataSourceStat: true
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  #aop配置
  aop:
    auto: true
    proxy-target-class: true

#mybatis-plus的配置
mybatis-plus:
  type-aliases-package: com.zdk.MyBlog.model
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl
    map-underscore-to-camel-case: true
    cache-enabled: true
  global-config:
    db-config:
      #logic-delete-field: deleted 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1
#      logic-not-delete-value: 0
      table-prefix: blog_

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


#又拍云配置
up-yun:
  bucketName: zdk-blog-image
  userName: fengzhu
  password: x04vgrvGFyge5opzOgdgXcARS1eYfekA
  saveKey: /zdk-blog-image/
  imageParam: /fw/1100/unsharp/true/quality/100/format/png

#日志配置
logging:
  config: classpath:log4j2.xml
